services:
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    ports:
      - "8081:8081"

  aas-web-ui:
    image: eclipsebasyx/aas-gui:v2-240913
    container_name: aas-web-ui
    ports:
      - "3000:3000"
    depends_on:
      - aas-env
